export const keys = {
  Backquote: {
    line: 1,
    en: "`",
    ru: "ё",
    enShift: "~",
    ruShift: "Ё",
    additionClasses: ["black", "space"],
    shiftable: true,
  },
  Digit1: {
    line: 1,
    en: "1",
    ru: "1",
    enShift: "!",
    ruShift: "!",
    additionClasses: [],
    shiftable: true,
  },
  Digit2: {
    line: 1,
    en: "2",
    ru: "2",
    enShift: "@",
    ruShift: '"',
    additionClasses: [],
    shiftable: true,
  },
  Digit3: {
    line: 1,
    en: "3",
    ru: "3",
    enShift: "#",
    ruShift: "№",
    additionClasses: [],
    shiftable: true,
  },
  Digit4: {
    line: 1,
    en: "4",
    ru: "4",
    enShift: "$",
    ruShift: ";",
    additionClasses: [],
    shiftable: true,
  },
  Digit5: {
    line: 1,
    en: "5",
    ru: "5",
    enShift: "%",
    ruShift: "%",
    additionClasses: [],
    shiftable: true,
  },
  Digit6: {
    line: 1,
    en: "6",
    ru: "6",
    enShift: "^",
    ruShift: ":",
    additionClasses: [],
    shiftable: true,
  },
  Digit7: {
    line: 1,
    en: "7",
    ru: "7",
    enShift: "&",
    ruShift: "?",
    additionClasses: [],
    shiftable: true,
  },
  Digit8: {
    line: 1,
    en: "8",
    ru: "8",
    enShift: "*",
    ruShift: "*",
    additionClasses: [],
    shiftable: true,
  },
  Digit9: {
    line: 1,
    en: "9",
    ru: "9",
    enShift: "(",
    ruShift: "(",
    additionClasses: [],
    shiftable: true,
  },
  Digit0: {
    line: 1,
    en: "0",
    ru: "0",
    enShift: ")",
    ruShift: ")",
    additionClasses: [],
    shiftable: true,
  },
  Minus: {
    line: 1,
    en: "-",
    ru: "-",
    enShift: "_",
    ruShift: "_",
    additionClasses: [],
    shiftable: true,
  },
  Equal: {
    line: 1,
    en: "=",
    ru: "=",
    enShift: "+",
    ruShift: "+",
    additionClasses: [],
    shiftable: true,
  },
  Backspace: {
    line: 1,
    en: "Backspace",
    ru: "Backspace",
    additionClasses: ["black", "backspace"],
  },
  Tab: {
    line: 2,
    en: "Tab",
    ru: "Tab",
    additionClasses: ["black", "tab"],
  },
  KeyQ: {
    line: 2,
    en: "Q",
    ru: "Й",
    additionClasses: [],
  },
  KeyW: {
    line: 2,
    en: "W",
    ru: "Ц",
    additionClasses: [],
  },
  KeyE: {
    line: 2,
    en: "E",
    ru: "У",
    additionClasses: [],
  },
  KeyR: {
    line: 2,
    en: "R",
    ru: "К",
    additionClasses: [],
  },
  KeyT: {
    line: 2,
    en: "T",
    ru: "Е",
    additionClasses: [],
  },
  KeyY: {
    line: 2,
    en: "Y",
    ru: "Н",
    additionClasses: [],
  },
  KeyU: {
    line: 2,
    en: "U",
    ru: "Г",
    additionClasses: [],
  },
  KeyI: {
    line: 2,
    en: "I",
    ru: "Ш",
    additionClasses: [],
  },
  KeyO: {
    line: 2,
    en: "O",
    ru: "Щ",
    additionClasses: [],
  },
  KeyP: {
    line: 2,
    en: "P",
    ru: "З",
    additionClasses: [],
  },
  BracketLeft: {
    line: 2,
    en: "[",
    ru: "х",
    enShift: "{",
    ruShift: "Х",
    additionClasses: [],
    shiftable: true,
  },
  BracketRight: {
    line: 2,
    en: "]",
    ru: "ъ",
    enShift: "}",
    ruShift: "Ъ",
    additionClasses: [],
    shiftable: true,
  },
  Backslash: {
    line: 2,
    en: "\\",
    ru: "\\",
    enShift: "|",
    ruShift: "/",
    additionClasses: [],
    shiftable: true,
  },
  Delete: {
    line: 2,
    en: "Delete",
    ru: "Delete",
    additionClasses: ["del", "black"],
  },
  CapsLock: {
    line: 3,
    en: "Caps Lock",
    ru: "Caps Lock",
    additionClasses: ["caps", "black"],
  },
  KeyA: {
    line: 3,
    en: "A",
    ru: "Ф",
    additionClasses: [],
  },
  KeyS: {
    line: 3,
    en: "S",
    ru: "Ы",
    additionClasses: [],
  },
  KeyD: {
    line: 3,
    en: "D",
    ru: "В",
    additionClasses: [],
  },
  KeyF: {
    line: 3,
    en: "F",
    ru: "А",
    additionClasses: [],
  },
  KeyG: {
    line: 3,
    en: "G",
    ru: "П",
    additionClasses: [],
  },
  KeyH: {
    line: 3,
    en: "H",
    ru: "Р",
    additionClasses: [],
  },
  KeyJ: {
    line: 3,
    en: "J",
    ru: "О",
    additionClasses: [],
  },
  KeyK: {
    line: 3,
    en: "K",
    ru: "Л",
    additionClasses: [],
  },
  KeyL: {
    line: 3,
    en: "L",
    ru: "Д",
    additionClasses: [],
  },
  Semicolon: {
    line: 3,
    en: ";",
    ru: "Ж",
    enShift: ":",
    ruShift: "Ж",
    additionClasses: [],
    shiftable: true,
  },
  Semicolon: {
    line: 3,
    en: ";",
    ru: "Ж",
    enShift: ":",
    ruShift: "Ж",
    additionClasses: [],
    shiftable: true,
  },
  Quote: {
    line: 3,
    en: "'",
    ru: "Э",
    enShift: '"',
    ruShift: "Э",
    additionClasses: [],
    shiftable: true,
  },
  Enter: {
    line: 3,
    en: "Enter",
    ru: "Enter",
    additionClasses: ["enter", "black"],
  },
  ShiftLeft: {
    line: 4,
    en: "Shift",
    ru: "Shift",
    additionClasses: ["left-shift", "black"],
  },
  Backslash: {
    line: 4,
    en: "\\",
    ru: "\\",
    enShift: "|",
    ruShift: "/",
    additionClasses: [],
    shiftable: true,
  },
  KeyZ: {
    line: 4,
    en: "Z",
    ru: "Я",
    additionClasses: [],
  },
  KeyX: {
    line: 4,
    en: "X",
    ru: "Ч",
    additiSonClasses: [],
  },
  KeyC: {
    line: 4,
    en: "C",
    ru: "С",
    additionClasses: [],
  },
  KeyV: {
    line: 4,
    en: "V",
    ru: "М",
    additionClasses: [],
  },
  KeyB: {
    line: 4,
    en: "B",
    ru: "И",
    additionClasses: [],
  },
  KeyN: {
    line: 4,
    en: "N",
    ru: "Т",
    additionClasses: [],
  },
  KeyM: {
    line: 4,
    en: "M",
    ru: "Ь",
    additionClasses: [],
  },
  Comma: {
    line: 4,
    en: ",",
    ru: "Б",
    enShift: "<",
    ruShift: "Б",
    additionClasses: [],
    shiftable: true,
  },
  Period: {
    line: 4,
    en: ".",
    ru: "Ю",
    enShift: ">",
    ruShift: "Ю",
    additionClasses: [],
    shiftable: true,
  },
  Slash: {
    line: 4,
    en: "/",
    ru: ".",
    enShift: "?",
    ruShift: ",",
    additionClasses: [],
    shiftable: true,
  },
  ArrowUp: {
    line: 4,
    en: "🠑",
    ru: "🠑",
    additionClasses: ["black"],
  },
  ShiftRight: { line: 4, en: "Shift", ru: "Shift", additionClasses: ["black"] },
  ControlLeft: {
    line: 5,
    en: "Ctrl",
    ru: "Ctrl",
    additionClasses: ["ctrl", "black"],
  },
  MetaLeft: {
    line: 5,
    en: "Win",
    ru: "Win",
    additionClasses: ["black"],
  },
  AltLeft: {
    line: 5,
    en: "Alt",
    ru: "Alt",
    additionClasses: ["black"],
  },
  Space: {
    line: 5,
    en: "Space",
    ru: "Space",
    additionClasses: ["space"],
  },
  AltRight: {
    line: 5,
    en: "Alt",
    ru: "Alt",
    additionClasses: ["black"],
  },
  ControlRight: {
    line: 5,
    en: "Ctrl",
    ru: "Ctrl",
    additionClasses: ["ctrl", "black"],
  },
  ArrowLeft: {
    line: 5,
    en: "🠐",
    ru: "🠐",
    additionClasses: ["black"],
  },
  ArrowDown: {
    line: 5,
    en: "🠓",
    ru: "🠓",
    additionClasses: ["black"],
  },
  ArrowRight: {
    line: 5,
    en: "🠒",
    ru: "🠒",
    additionClasses: ["black"],
  },
};
