export default {
  Backquote: {
    line: 1,
    en: '`',
    ru: 'ё',
    enShift: '~',
    ruShift: 'Ё',
    additionClasses: ['black'],
    shiftable: true,
    isSymbol: true,
  },
  Digit1: {
    line: 1,
    en: '1',
    ru: '1',
    enShift: '!',
    ruShift: '!',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Digit2: {
    line: 1,
    en: '2',
    ru: '2',
    enShift: '@',
    ruShift: '"',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Digit3: {
    line: 1,
    en: '3',
    ru: '3',
    enShift: '#',
    ruShift: '№',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Digit4: {
    line: 1,
    en: '4',
    ru: '4',
    enShift: '$',
    ruShift: ';',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Digit5: {
    line: 1,
    en: '5',
    ru: '5',
    enShift: '%',
    ruShift: '%',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Digit6: {
    line: 1,
    en: '6',
    ru: '6',
    enShift: '^',
    ruShift: ':',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Digit7: {
    line: 1,
    en: '7',
    ru: '7',
    enShift: '&',
    ruShift: '?',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Digit8: {
    line: 1,
    en: '8',
    ru: '8',
    enShift: '*',
    ruShift: '*',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Digit9: {
    line: 1,
    en: '9',
    ru: '9',
    enShift: '(',
    ruShift: '(',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Digit0: {
    line: 1,
    en: '0',
    ru: '0',
    enShift: ')',
    ruShift: ')',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Minus: {
    line: 1,
    en: '-',
    ru: '-',
    enShift: '_',
    ruShift: '_',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Equal: {
    line: 1,
    en: '=',
    ru: '=',
    enShift: '+',
    ruShift: '+',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Backspace: {
    line: 1,
    en: 'Backspace',
    ru: 'Backspace',
    additionClasses: ['black', 'backspace'],
  },
  Tab: {
    line: 2,
    en: 'Tab',
    ru: 'Tab',
    additionClasses: ['black', 'tab'],
  },
  KeyQ: {
    line: 2,
    en: 'q',
    ru: 'й',
    enShift: 'Q',
    ruShift: 'Й',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyW: {
    line: 2,
    en: 'w',
    ru: 'ц',
    enShift: 'W',
    ruShift: 'Ц',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyE: {
    line: 2,
    en: 'e',
    ru: 'у',
    enShift: 'E',
    ruShift: 'У',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyR: {
    line: 2,
    en: 'r',
    ru: 'к',
    enShift: 'R',
    ruShift: 'К',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyT: {
    line: 2,
    en: 't',
    ru: 'е',
    enShift: 'T',
    ruShift: 'Е',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyY: {
    line: 2,
    en: 'y',
    ru: 'н',
    enShift: 'Y',
    ruShift: 'Н',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyU: {
    line: 2,
    en: 'u',
    ru: 'г',
    enShift: 'U',
    ruShift: 'Г',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyI: {
    line: 2,
    en: 'i',
    ru: 'ш',
    enShift: 'I',
    ruShift: 'Ш',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyO: {
    line: 2,
    en: 'o',
    ru: 'щ',
    enShift: 'O',
    ruShift: 'Щ',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyP: {
    line: 2,
    en: 'p',
    ru: 'з',
    enShift: 'P',
    ruShift: 'З',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  BracketLeft: {
    line: 2,
    en: '[',
    ru: 'х',
    enShift: '{',
    ruShift: 'Х',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  BracketRight: {
    line: 2,
    en: ']',
    ru: 'ъ',
    enShift: '}',
    ruShift: 'Ъ',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Backslash: {
    line: 2,
    en: '\\',
    ru: '\\',
    enShift: '|',
    ruShift: '/',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Delete: {
    line: 2,
    en: 'Delete',
    ru: 'Delete',
    additionClasses: ['del', 'black'],
  },
  CapsLock: {
    line: 3,
    en: 'Caps Lock',
    ru: 'Caps Lock',
    additionClasses: ['caps', 'black'],
  },
  KeyA: {
    line: 3,
    en: 'a',
    ru: 'ф',
    enShift: 'A',
    ruShift: 'Ф',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyS: {
    line: 3,
    en: 's',
    ru: 'ы',
    enShift: 'S',
    ruShift: 'Ы',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyD: {
    line: 3,
    en: 'd',
    ru: 'в',
    enShift: 'D',
    ruShift: 'В',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyF: {
    line: 3,
    en: 'f',
    ru: 'а',
    enShift: 'F',
    ruShift: 'А',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyG: {
    line: 3,
    en: 'g',
    ru: 'п',
    enShift: 'G',
    ruShift: 'П',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyH: {
    line: 3,
    en: 'h',
    ru: 'р',
    enShift: 'H',
    ruShift: 'Р',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyJ: {
    line: 3,
    en: 'j',
    ru: 'о',
    enShift: 'J',
    ruShift: 'О',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyK: {
    line: 3,
    en: 'k',
    ru: 'л',
    enShift: 'K',
    ruShift: 'Л',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyL: {
    line: 3,
    en: 'l',
    ru: 'д',
    enShift: 'L',
    ruShift: 'Д',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  Semicolon: {
    line: 3,
    en: ';',
    ru: 'ж',
    enShift: ':',
    ruShift: 'Ж',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Quote: {
    line: 3,
    en: "'",
    ru: 'э',
    enShift: '"',
    ruShift: 'Э',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Enter: {
    line: 3,
    en: 'Enter',
    ru: 'Enter',
    additionClasses: ['enter', 'black'],
  },
  ShiftLeft: {
    line: 4,
    en: 'Shift',
    ru: 'Shift',
    additionClasses: ['left-shift', 'black'],
  },
  KeyZ: {
    line: 4,
    en: 'z',
    ru: 'я',
    enShift: 'Z',
    ruShift: 'Я',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyX: {
    line: 4,
    en: 'x',
    ru: 'ч',
    enShift: 'X',
    ruShift: 'Ч',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyC: {
    line: 4,
    en: 'c',
    ru: 'с',
    enShift: 'C',
    ruShift: 'С',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyV: {
    line: 4,
    en: 'v',
    ru: 'м',
    enShift: 'V',
    ruShift: 'М',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyB: {
    line: 4,
    en: 'b',
    ru: 'и',
    enShift: 'B',
    ruShift: 'И',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyN: {
    line: 4,
    en: 'n',
    ru: 'т',
    enShift: 'N',
    ruShift: 'Т',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  KeyM: {
    line: 4,
    en: 'm',
    ru: 'ь',
    enShift: 'M',
    ruShift: 'Ь',
    additionClasses: [],
    isSymbol: true,
    shiftable: true,
  },
  Comma: {
    line: 4,
    en: ',',
    ru: 'б',
    enShift: '<',
    ruShift: 'Б',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Period: {
    line: 4,
    en: '.',
    ru: 'ю',
    enShift: '>',
    ruShift: 'Ю',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  Slash: {
    line: 4,
    en: '/',
    ru: '.',
    enShift: '?',
    ruShift: ',',
    additionClasses: [],
    shiftable: true,
    isSymbol: true,
  },
  ArrowUp: {
    line: 4,
    en: '\u{2191}',
    ru: '\u{2191}',
    additionClasses: ['black'],
    isSymbol: true,
  },
  ShiftRight: {
    line: 4,
    en: 'Shift',
    ru: 'Shift',
    additionClasses: ['right-shift', 'black'],
  },
  ControlLeft: {
    line: 5,
    en: 'Ctrl',
    ru: 'Ctrl',
    additionClasses: ['ctrl', 'black'],
  },
  MetaLeft: {
    line: 5,
    en: 'Win',
    ru: 'Win',
    additionClasses: ['black'],
  },
  AltLeft: {
    line: 5,
    en: 'Alt',
    ru: 'Alt',
    additionClasses: ['black'],
  },
  Space: {
    line: 5,
    en: 'Space',
    ru: 'Space',
    additionClasses: ['space'],
  },
  AltRight: {
    line: 5,
    en: 'Alt',
    ru: 'Alt',
    additionClasses: ['black'],
  },
  ControlRight: {
    line: 5,
    en: 'Ctrl',
    ru: 'Ctrl',
    additionClasses: ['ctrl', 'black'],
  },
  ArrowLeft: {
    line: 5,
    en: '\u{2190}',
    ru: '\u{2190}',
    additionClasses: ['black'],
    isSymbol: true,
  },
  ArrowDown: {
    line: 5,
    en: '\u{2193}',
    ru: '\u{2193}',
    additionClasses: ['black'],
    isSymbol: true,
  },
  ArrowRight: {
    line: 5,
    en: '\u{2192}',
    ru: '\u{2192}',
    additionClasses: ['black'],
    isSymbol: true,
  },
};
